worker_processes  1;

pid        logs/nginx.pid;
error_log  logs/error.log warn;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log    logs/access.log;
    sendfile      on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name local.mecca.test;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name local.mecca.test;

        ssl_certificate      D:/projects/mecca-web-app/.local/certs/local.mecca.test.pem;
        ssl_certificate_key  D:/projects/mecca-web-app/.local/certs/local.mecca.test-key.pem;

        location /api/ {
            proxy_pass         http://localhost:5238/api/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Forwarded-Proto https;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $host;
        }

        location / {
            proxy_pass         http://localhost:5173/;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Forwarded-Proto https;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }
    }
}
